name: ${name}
version: ${version}
main: io.nexstudios.nexus.bukkit.Nexus
api-version: '1.21.4'
softdepend:
  - PlaceholderAPI
  - Vault
libraries:
  - redis.clients:jedis:5.2.0
  - com.zaxxer:HikariCP:6.3.0
  - org.mariadb.jdbc:mariadb-java-client:3.5.3
  - commons-lang:commons-lang:2.6
  - org.bstats:bstats-bukkit:3.0.2