name: ${name}
version: ${version}
main: io.nexstudios.nexus.bukkit.NexusPlugin
api-version: '1.21'
softdepend:
  - PlaceholderAPI
  - Vault
  - Nexo
  - eco
  - EcoItems
  - MythicMobs
  - MMOItems
  - WorldGuard
  - Luckperms
libraries:
  - redis.clients:jedis:5.2.0
  - com.zaxxer:HikariCP:6.3.0
  - org.mariadb.jdbc:mariadb-java-client:3.5.3
  - commons-lang:commons-lang:2.6
  - org.bstats:bstats-bukkit:3.0.2